export const ENGINE_NAMES = {
  v8: "V8",
  v8_exp: "V8 🧪⚙️",
  sm: "SpiderMonkey",
  sm_exp: "SpiderMonkey 🧪⚙️",
  jsc: "JavaScriptCore",
  jsc_exp: "JavaScriptCore 🧪⚙️",
  hermes: "Hermes",
  chakra: "ChakraCore",
  qjs: "QuickJS",
  qjs_ng: "QuickJS NG",
  libjs: "LibJS",
  graaljs: "GraalJS",
  graaljs_exp: "GraalJS 🧪⚙️",
  xs: "XS",
  rhino: "Rhino",
  engine262: "engine262",
  boa: "Boa",
  kiesel: "Kiesel",
  porffor: "Porffor",
  nova: "Nova",
  njs: "NJS",
  bali: "Bali",
  babel: "Babel",
  swc: "SWC",
  sucrase: "Sucrase",
} as const;

export const ENGINE_INFO = {
  v8: "Chromium's JS engine, also used by Node and Deno",
  v8_exp: "V8 with experimental options",
  sm: "Gecko's JS engine",
  sm_exp: "SpiderMonkey with experimental options",
  jsc: "WebKit's JS engine",
  jsc_exp: "JavaScriptCore with experimental options",
  hermes: "Made for and used by React Native",
  chakra: "Former JS engine for Edge",
  libjs: "JS engine from SerenityOS, also used in Ladybird browser",
  graaljs: "Built on GraalVM",
  graaljs_exp: "GraalJS with experimental options",
  engine262: "ECMA262 in JavaScript!",
  rhino: "Java JS engine by Mozilla",
  boa: "Experimental embeddable JS engine in Rust",
  kiesel: "New JS engine written in Zig",
  porffor: "New experimental AOT JS -> Wasm compiler, in JS",
  nova: "A new JS engine written in Rust exploring a data-oriented design",
  njs: "A subset of the JavaScript language to use in nginx",
  bali: "A new experimental JavaScript engine written in Nim",
  babel: "Babel 7 + core-js 3 running on Node 0.10 (ES5)",
  swc: "SWC + core-js 3 running on Node 0.10 (ES5)",
  sucrase: "Sucrase + core-js running on Node 0.10 (ES5) - for curiosity",
} as const;

export const ENG_SHORT_NAMES = {
  v8: "V8",
  v8_exp: "V8🧪",
  sm: "SM",
  sm_exp: "SM🧪",
  jsc: "JSC",
  jsc_exp: "JSC🧪",
  hermes: "Hermes",
  chakra: "Chakra",
  qjs: "QJS",
  qjs_ng: "QJS-NG",
  libjs: "LJS",
  graaljs: "Graal",
  graaljs_exp: "Graal🧪",
  xs: "XS",
  rhino: "Rhino",
  engine262: "e262",
  boa: "Boa",
  kiesel: "Kiesel",
  porffor: "Porf",
  nova: "Nova",
  njs: "NJS",
  bali: "Bali",
  babel: "Babel",
  swc: "SWC",
  sucrase: "Sucrase",
} as const;

export const CATEGORIES = {
  babel: "transformers",
  swc: "transformers",
  sucrase: "transformers",
} as const;

export const ENG_ORDER = [
  "v8",
  "v8_exp",
  "jsc",
  "jsc_exp",
  "hermes",
  "sm",
  "sm_exp",
  "qjs",
  "qjs_ng",
  "libjs",
  "chakra",
  "graaljs",
  "graaljs_exp",
  "xs",
  "rhino",
  "boa",
  "kiesel",
  "porffor",
  "nova",
  "njs",
  "engine262",
  "bali",
  "babel",
  "swc",
  "sucrase",
];

export const DEFAULT_SELECTED_ENG = [
  "v8",
  "jsc",
  "hermes",
  "babel",
  "sm",
];

export const ES_EDITIONS = {
  5: "ES5",
  6: "ES6",
  7: "ES2016",
  8: "ES2017",
  9: "ES2018",
  10: "ES2019",
  11: "ES2020",
  12: "ES2021",
  13: "ES2022",
  14: "ES2023",
  15: "ES2024",
  16: "ES2025",
  17: "ES2026",
  "undefined": "ESNext",
};
